# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180114_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='nonactive',
            field=models.NullBooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
