# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180114_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='New title', max_length=30),
            preserve_default=False,
        ),
    ]
