# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-14 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
