# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20180115_1951'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postmodel',
            unique_together=set([('title', 'description')]),
        ),
    ]
