# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180115_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='postmodel',
            unique_together=set([]),
        ),
    ]
