# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 19:18
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180115_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='author_email',
            field=models.CharField(blank=True, max_length=240, null=True, validators=[blog.validators.validate_author_email, blog.validators.validate_admin]),
        ),
    ]
