# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180115_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='second_author',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
    ]
