# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_postmodel_second_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='second_author',
            field=models.EmailField(blank=True, max_length=240, null=True),
        ),
    ]
