# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_postmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(error_messages={'unique': 'This title is not unique. Please try again'}, max_length=30, unique=True, verbose_name='Title'),
        ),
    ]
