# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180121_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
